export const CHANGE_SEARCH_FILTERS = "CHANGE_SEARCH_FILTERS";
export const CHANGE_NAVIGATION_FILTERS = "CHANGE_NAVIGATION_FILTERS";
export const SEARCH_RESULTS = "SEARCH_RESULTS";
export const SET_MOVIE = "GET_MOVIE";
export const CHANGE_QUERY = "CHANGE_QUERY";
export const FILTERED_BY_GENRE = "FILTERED_BY_GENRE";